Update 10_load_cuda_env
Co-authored-by: scott-vsi <scott.richardson@visionsystemsinc.com>

diff --git a/10_load_cuda_env b/10_load_cuda_env
--- a/10_load_cuda_env
+++ b/10_load_cuda_env
@@ -17,7 +17,7 @@ elif command -v apt-get 2>&1 > /dev/null; then
     source "${file}"
   done
 else
-  echo "Unable to ID os. Please amend this script" >&2
+  echo "Unable to ID OS. Please amend this script" >&2
   exit 1
 fi
 
