update to exactly the planned form of download_to_stdout

diff --git a/30_get-pipenv b/30_get-pipenv
--- a/30_get-pipenv
+++ b/30_get-pipenv
@@ -64,7 +64,7 @@ fi
 #**
 # .. function:: download_to_stdout
 #
-# Download a file from the internet and output stream to stdout.  Adapted from ``${VSI_COMMON_DIR}/linux/web_tools.bsh```
+# Download a file from the internet and output stream to stdout
 #
 # :Arguments: ``$1`` - URL to download
 # :Output: ``stdout`` - Binary stream of the url
@@ -73,36 +73,48 @@ fi
 #
 # 1. ``wget`` using ``wget -qO -``
 # 2. ``curl`` using ``curl -fsSL``
-# 3. ``${PIPENV_PYTHON}`` using the ``requests``, ```urllib2``, or ``urllib`` library
+# 3. `python`` using the ``requests``, ```urllib2``, or ``urllib`` library
+# 4. ``ruby`` using the ``open-uri`` library
+# 5. ``perl`` using the ``LWP::Simple`` library
 #**
-function download_to_stdout()
-{
-  local success=1
-  if command -v wget &> /dev/null; then
-    wget "${1}" -qO - && success=0 || success=$?
-  fi
-  if [ "${success}" != "0" ] && command -v curl &> /dev/null; then
-    curl -fsSL "${1}" && success=0 || success=$?
-  fi
-  if [ "${success}" != "0" ]; then
-    "${PIPENV_PYTHON}" -c 'if True:
-        try:
-          import requests
-          os.write(1, requests.get("'"${1}"'").content)
-        except:
-          try:
-            import urllib2 as u
-          except:
-            import urllib.request as u
-          import os
-          os.write(1,u.urlopen("'"${1}"'").read())
-        ' && success=0 || success=$?
-  fi
-  if [ "${success}" != "0" ]; then
-    echo "Cannot download a file" >&2
-    return 2
-  fi
-}
+if [ -f "${VSI_COMMON_DIR-}/linux/webtools.bsh" ]; then
+  source "${VSI_COMMON_DIR}/linux/webtools.bsh"
+else
+  function download_to_stdout()
+  {
+    local success=1
+    if command -v wget &> /dev/null; then
+      wget "${1}" -qO - && success=0 || success=$?
+    fi
+    if [ "${success}" != "0" ] && command -v curl &> /dev/null; then
+      curl -fsSL "${1}"  && success=0 || success=$?
+    fi
+    if [ "${success}" != "0" ] && command -v python &> /dev/null; then
+      "${PYTHON-python}" -c  'if True:
+                    try:
+                      import requests
+                      os.write(1, requests.get("'"${1}"'").content)
+                    except:
+                      try:
+                        import urllib2 as u
+                      except:
+                        import urllib.request as u
+                      import os
+                      os.write(1,u.urlopen("'"${1}"'").read())' && success=0 || success=$?
+    fi
+    if [ "${success}" != "0" ] && command -v ruby &> /dev/null; then
+      ruby -e "require 'open-uri'; URI.open('${1}', 'rb') do |read_file|; \$stdout.write(read_file.read); end" && success=0 || success=$?
+    fi
+    if [ "${success}" != "0" ] && command -v perl &> /dev/null; then
+      # Not all Perls have LWP installed
+      perl -MLWP::Simple -e "getprint '${1}'" && success=0 || success=$?
+    fi
+    if [ "${success}" != "0" ]; then
+      echo "Cannot download a file" >&2
+      return 2
+    fi
+  }
+fi
 
 
 #**
@@ -165,7 +177,7 @@ install_pipenv()
 
       # download to file
       virtualenv_pyz="${tmp_dir}/virtualenv.pyz"
-      download_to_stdout "${url}" > "${virtualenv_pyz}"    
+      PYTHON="${PIPENV_PYTHON}" download_to_stdout "${url}" > "${virtualenv_pyz}"    
     fi
 
     # Temp fix for https://github.com/pypa/virtualenv/issues/1949
