30_get-pipenv add RECIPE_* environment variables (allow user to avoid conflict with PIPENV_VERSION variables used by pipenv)

diff --git a/30_get-pipenv b/30_get-pipenv
--- a/30_get-pipenv
+++ b/30_get-pipenv
@@ -169,29 +169,32 @@ fi
 #
 # While virtualenv documentation recommends download of the virtualenv zipapp file from https://bootstrap.pypa.io/virtualenv, this script instead downloads from https://github.com/pypa/get-virtualenv/ which offered versioned zipapp files.  This avoids possible breaking changes introduced at the pypa bootstrap site.
 #
-# :Arguments: [``$1``] - The location of the virtualenv, defaults to ``${PIPENV_VIRTUALENV-${HOME}/pipenv}``
-# :Parameters: * ``PIPENV_PYTHON`` - Optionally specify which python you want to use. Default is to favor python3, trying ``python3``, ``python``, then finally falling back to ``python2``.
-#              * ``PIPENV_VERSION`` - The version of pipenv to install, defaults - ``2018.11.26``
-#              * ``VIRTUALENV_PYZ`` - Name of downloaded ``virtualenv.pyz``, else it will attempt to download it itself.
-#              * ``VIRTUALENV_VERSION`` - The version of virtualenv to use, affecting both the virtualenv zipapp version and the virtualenv version used by pipenv environment.  defaults to ``20.0.33``
+# Prefer use of ``RECIPE_*``` environment variables (e.g., prefer ``RECIPE_PIPENV_VERSION`` over ``PIPENV_VERSION``). Pipenv uses ``PIPENV_{FLAG_NAME}`` to control command line execution via environment variables, as per https://github.com/pypa/pipenv/blob/master/CHANGELOG.rst#features--improvements-4. Use of ``PIPENV_VERSION`` to control the installed pipenv version may cause subsequent calls to pipenv to fail with the error ``Error: Invalid value for '--version': 2020.11.15 is not a valid boolean``.
+#
+# :Arguments: [``$1``] - The location of the virtualenv, defaults to ``${RECIPE_PIPENV_VIRTUALENV-${PIPENV_VIRTUALENV-${HOME}/pipenv}}``
+# :Parameters: * ``RECIPE_PIPENV_PYTHON`` or ``PIPENV_PYTHON`` - Optionally specify which python you want to use. Default is to favor python3, trying ``python3``, ``python``, then finally falling back to ``python2``.
+#              * ``RECIPE_PIPENV_VERSION`` or ``PIPENV_VERSION`` - The version of pipenv to install, defaults - ``2020.11.15``
+#              * ``RECIPE_VIRTUALENV_PYZ`` or ``VIRTUALENV_PYZ`` - Name of downloaded ``virtualenv.pyz``, else it will attempt to download it itself.
+#              * ``RECIPE_VIRTUALENV_VERSION`` or ``VIRTUALENV_VERSION`` - The version of virtualenv to use, affecting both the virtualenv zipapp version and the virtualenv version used by pipenv environment.  defaults to ``20.4.5``
+#
 #**
 install_pipenv()
 {
   # python executable
-  : ${PIPENV_PYTHON:="$( (command -v python3 || command -v python || command -v python2) | head -n 1)"}
-  [ -n "${PIPENV_PYTHON}" ] # Make sure python was found
+  local python_exe="${RECIPE_PIPENV_PYTHON:-${PIPENV_PYTHON:-"$( (command -v python3 || command -v python || command -v python2) | head -n 1)"}}"
+  [ -n "${python_exe}" ] # Make sure python was found
 
   # setup
-  local output_dir="${1-${PIPENV_VIRTUALENV-${HOME}/pipenv}}"
-  local pipenv_ver="${PIPENV_VERSION:-2018.11.26}"
-  local virtualenv_pyz=${VIRTUALENV_PYZ-}
-  local virtualenv_version=${VIRTUALENV_VERSION:-20.0.33}
+  local output_dir="${1-${RECIPE_PIPENV_VIRTUALENV-${PIPENV_VIRTUALENV-${HOME}/pipenv}}}"
+  local pipenv_ver="${RECIPE_PIPENV_VERSION:-${PIPENV_VERSION:-2020.11.15}}"
+  local virtualenv_pyz="${RECIPE_VIRTUALENV_PYZ:-${VIRTUALENV_PYZ:-}}"
+  local virtualenv_version="${RECIPE_VIRTUALENV_VERSION:-${VIRTUALENV_VERSION:-20.4.5}}"
 
   # use existing virtualenv
-  virtualenv_ver="$("${PIPENV_PYTHON}" -m virtualenv --version 2>/dev/null || :)"
+  virtualenv_ver="$("${python_exe}" -m virtualenv --version 2>/dev/null || :)"
   if [ -n "${virtualenv_ver}" ]; then
     echo "Found virtualenv (${virtualenv_ver})" >&2
-    "${PIPENV_PYTHON}" -m virtualenv "${output_dir}"
+    "${python_exe}" -m virtualenv "${output_dir}"
 
   # use virtualenv zipapp
   # https://virtualenv.pypa.io/en/latest/installation.html#via-zipapp
@@ -215,14 +218,14 @@ install_pipenv()
 
       # download to file
       virtualenv_pyz="${tmp_dir}/virtualenv.pyz"
-      PYTHON="${PIPENV_PYTHON}" download_to_file "${url}" "${virtualenv_pyz}"
+      PYTHON="${python_exe}" download_to_file "${url}" "${virtualenv_pyz}"
     fi
 
     # Temp fix for https://github.com/pypa/virtualenv/issues/1949
     virtualenv_pyz="$(real_path "${virtualenv_pyz}")"
 
     # create output virtualenv
-    "${PIPENV_PYTHON}" "${virtualenv_pyz}" "${output_dir}"
+    "${python_exe}" "${virtualenv_pyz}" "${output_dir}"
 
     # cleanup
     rm -rf "${tmp_dir}" || :
