30_get-pipenv - error message if python is missing

diff --git a/30_get-pipenv b/30_get-pipenv
--- a/30_get-pipenv
+++ b/30_get-pipenv
@@ -182,7 +182,12 @@ install_pipenv()
 {
   # python executable
   local python_exe="${RECIPE_PIPENV_PYTHON:-${PIPENV_PYTHON:-"$( (command -v python3 || command -v python || command -v python2) | head -n 1)"}}"
-  [ -n "${python_exe}" ] # Make sure python was found
+
+  # Make sure python was found
+  if [ -n "${python_exe}" ]; then
+    echo "install_pipenv cannot find python executable. Try setting RECIPE_PIPENV_PYTHON to point to python" >&2
+    return 1
+  fi
 
   # setup
   local output_dir="${1-${RECIPE_PIPENV_VIRTUALENV-${PIPENV_VIRTUALENV-${HOME}/pipenv}}}"
